// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9V7WXxeEZCzswqzS3Y_G2nXGRANeyFyE',
    appId: '1:1083184513067:web:b5e99f541355d6610f6a6e',
    messagingSenderId: '1083184513067',
    projectId: 'artteacher-d355a',
    authDomain: 'artteacher-d355a.firebaseapp.com',
    storageBucket: 'artteacher-d355a.appspot.com',
    measurementId: 'G-DPBNRW8Z1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANyiPnBlHW23FtaoCRgSX39S_iVXvE7OI',
    appId: '1:1083184513067:android:74af2dda60e7d4f10f6a6e',
    messagingSenderId: '1083184513067',
    projectId: 'artteacher-d355a',
    storageBucket: 'artteacher-d355a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqovppUO5ABFco6SgsLfpcrcO9eMaBNJ4',
    appId: '1:1083184513067:ios:f6cdfdd0df1150420f6a6e',
    messagingSenderId: '1083184513067',
    projectId: 'artteacher-d355a',
    storageBucket: 'artteacher-d355a.appspot.com',
    iosBundleId: 'com.example.artmaster',
  );
}
